# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Rob Dunn/Documents/School/ENEL 453/Lab1/LAB1_GIESBRECHT_DUNN_OH/LAB1_GIESBRECHT_DUNN_OH.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Rob Dunn/Documents/School/ENEL 453/Lab1/LAB1_GIESBRECHT_DUNN_OH/LAB1_GIESBRECHT_DUNN_OH.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/Rob Dunn/Documents/School/ENEL 453/Lab1/LAB1_GIESBRECHT_DUNN_OH/LAB1_GIESBRECHT_DUNN_OH.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {{C:/Users/Rob Dunn/Documents/School/ENEL 453/Lab1/LAB1_GIESBRECHT_DUNN_OH/Switch_logic.vhd}}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Rob Dunn/Documents/School/ENEL 453/Lab1/Basys3_Master_lab1.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Rob Dunn/Documents/School/ENEL 453/Lab1/Basys3_Master_lab1.xdc}}]


synth_design -top Switch_logic -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Switch_logic.dcp

catch { report_utilization -file Switch_logic_utilization_synth.rpt -pb Switch_logic_utilization_synth.pb }
