# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/arden.oh/project_3/project_3.cache/wt [current_project]
set_property parent.project_path C:/Users/arden.oh/project_3/project_3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/arden.oh/project_3/project_3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {//uc.ucalgary.ca/dfs/SSE/Users/arden.oh/Documents/453/Lab 5/PWM_DAC-2.vhd}
  {//uc.ucalgary.ca/dfs/SSE/Users/arden.oh/Documents/453/Lab 5/SAR.vhd}
  {//uc.ucalgary.ca/dfs/SSE/Users/arden.oh/Documents/453/Lab 5/SAR_DAC_top_module_testing.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{//uc.ucalgary.ca/dfs/SSE/Users/arden.oh/Documents/453/Lab 5/SAR_xdc.xdc}}
set_property used_in_implementation false [get_files {{//uc.ucalgary.ca/dfs/SSE/Users/arden.oh/Documents/453/Lab 5/SAR_xdc.xdc}}]


synth_design -top SAR_top_module -part xc7a35tcpg236-1


write_checkpoint -force -noxdef SAR_top_module.dcp

catch { report_utilization -file SAR_top_module_utilization_synth.rpt -pb SAR_top_module_utilization_synth.pb }
