# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {F:/LAB 5/Sub_ranging/Sub_ranging.cache/wt} [current_project]
set_property parent.project_path {F:/LAB 5/Sub_ranging/Sub_ranging.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {f:/LAB 5/Sub_ranging/Sub_ranging.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {//uc.ucalgary.ca/dfs/SSE/Users/arden.oh/Documents/453/Lab 5/Adder.vhd}
  {//uc.ucalgary.ca/dfs/SSE/Users/arden.oh/Documents/453/Lab 5/Clock_divider_50hz.vhd}
  {//uc.ucalgary.ca/dfs/SSE/Users/arden.oh/Documents/453/Lab 5/LSB_1.vhd}
  {//uc.ucalgary.ca/dfs/SSE/Users/arden.oh/Documents/453/Lab 5/MSB_1.vhd}
  {//uc.ucalgary.ca/dfs/SSE/Users/arden.oh/Documents/453/Lab 5/SUB_RANGING_TOP_MODULE.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{//uc.ucalgary.ca/dfs/SSE/Users/arden.oh/Documents/453/Lab 5/Subranging.xdc}}
set_property used_in_implementation false [get_files {{//uc.ucalgary.ca/dfs/SSE/Users/arden.oh/Documents/453/Lab 5/Subranging.xdc}}]


synth_design -top SUB_RANGING_TOP_MODULE -part xc7a35tcpg236-1


write_checkpoint -force -noxdef SUB_RANGING_TOP_MODULE.dcp

catch { report_utilization -file SUB_RANGING_TOP_MODULE_utilization_synth.rpt -pb SUB_RANGING_TOP_MODULE_utilization_synth.pb }
